{% set name = "excels2vensim" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/excels2vensim-{{ version }}.tar.gz
  sha256: 851d784631b7d50e7b10f42557291a44a25b6cb5f9943c7b4d00e66c922a2c09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pysd
    - python >=3.7

test:
  imports:
    - excels2vensim
    - excels2vensim.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/eneko.martin.martinez/excels2vensim
  summary: Easy write excel inputs in Vensim
  license: MIT
  license_file: LICENSE
  doc_url: https://excels2vensim.readthedocs.io/
  dev_url: https://gitlab.com/eneko.martin.martinez/excels2vensim

extra:
  recipe-maintainers:
    - enekomartinmartinez
